# Generated by Django 4.2.2 on 2023-07-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolarSystemPlanets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Solar System Planets",
                "verbose_name_plural": "Solar System Planets",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("abbreviation", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SSPMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(default=0.0, null=True)),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[
                            ("MASS", "Mass"),
                            ("DENSITY", "Density"),
                            ("DIAMETER", "Diameter"),
                            ("GRAVITY", "Gravity"),
                            ("ESCAPE_VELOCITY", "Escape_Velocity"),
                            ("DISTANCE", "Distance"),
                            ("PERIHELION", "Perihelion"),
                            ("APHELION", "Aphelion"),
                            ("ORBITAL_PERIOD", "Orbital_Period"),
                            ("ROTATIONAL_PERIOD", "Rotational_Period"),
                            ("ORBITAL_INCLINATION", "Orbital_Inclination"),
                            ("ECCENTRICITY", "Eccentricity"),
                            ("MEAN_TEMP", "Mean_Temp"),
                            ("SURFACE_PRESSURE", "Surface_Pressure"),
                            ("NUM_MOONS", "Num_Moons"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universe_db.solarsystemplanets",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universe_db.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solar System Planet Measurement",
                "verbose_name_plural": "Solar System Planet Measurements",
            },
        ),
    ]
