# Generated by Django 4.2.2 on 2023-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0004_alter_planetarysystems_spectral_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetarysystems",
            name="stellar_metallicity_ratio",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
