# Generated by Django 4.2.2 on 2023-07-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0006_alter_planetarysystems_options"),
        ("universe_db", "0007_auto_20230720_1943"),
    ]

    operations = []
