# Generated by Django 4.2.2 on 2023-07-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0009_planetarysystems_stellar_radius_and_more"),
        ("universe_db", "0010_auto_20230723_1617"),
    ]

    operations = []
