# Generated by Django 4.2.2 on 2023-07-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0011_merge_20230724_0208"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetarysystems",
            name="impact_parameter",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="planetarysystems",
            name="semimajor_axis",
            field=models.FloatField(null=True),
        ),
    ]
