# Generated by Django 4.2.2 on 2023-07-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0012_planetarysystems_impact_parameter_and_more"),
        ("universe_db", "0013_auto_20230724_0311"),
    ]

    operations = []
