# Generated by Django 4.2.2 on 2023-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0014_merge_20230724_0311"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoverPhoto",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sol", models.IntegerField()),
                ("camera", models.CharField(max_length=50)),
                ("img_src", models.URLField()),
                ("earth_date", models.DateField()),
                ("rover", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="sspmeasurement",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("MASS", "Mass"),
                    ("DENSITY", "Density"),
                    ("DIAMETER", "Diameter"),
                    ("GRAVITY", "Surface Gravity"),
                    ("ESCAPE_VELOCITY", "Escape Velocity"),
                    ("DISTANCE", "Distance"),
                    ("PERIHELION", "Perihelion"),
                    ("APHELION", "Aphelion"),
                    ("ORBITAL_PERIOD", "Orbit Period"),
                    ("ROTATIONAL_PERIOD", "Rotational Period"),
                    ("ORBITAL_INCLINATION", "Orbital Inclination"),
                    ("ECCENTRICITY", "Eccentricity"),
                    ("MEAN_TEMP", "Mean Temperature"),
                    ("SURFACE_PRESSURE", "Surface Pressure"),
                    ("NUM_MOONS", "Number of Moons"),
                ],
                max_length=100,
            ),
        ),
    ]
