# Generated by Django 4.2.2 on 2023-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe_db", "0015_roverphoto_alter_sspmeasurement_measurement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NASAPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("img_src", models.URLField()),
                ("thumb", models.URLField()),
                ("api_key", models.CharField(max_length=100)),
            ],
        ),
    ]
